### ISSUE TITLE
n_top_terms has no effect (or documentation of n_top_terms may be misleading)

### ISSUE THREAD

**Issue by bachl** [chainsawriot/oolong#29]
Hi again,
I started testing oolong now and I really like it. However, I am not sure whether I fully understand the behavior of the `n_top_terms` argument to `create_oolong()`. In my understanding, `n_top_terms` would define the number of "correct" terms in the word intrusion tests. The total number of words in the test would then be `n_top_terms` plus one intruder word. Yet changing `n_top_terms` does not change the number of words in the test.

```
oolong_test <- create_oolong(input_model = abstracts_stm, input_corpus = abstracts$text, n_top_terms = 5)
oolong_test$do_word_intrusion_test()
```
<img width="939" alt="Bildschirmfoto 2020-07-03 um 10 26 45" src="https://user-images.githubusercontent.com/6176704/86449009-d5f93d00-bd17-11ea-8405-c77f66341287.png">

```
oolong_test <- create_oolong(input_model = abstracts_stm, input_corpus = abstracts$text, n_top_terms = 10)
oolong_test$do_word_intrusion_test()
```
<img width="939" alt="Bildschirmfoto 2020-07-03 um 10 27 25" src="https://user-images.githubusercontent.com/6176704/86449080-ef9a8480-bd17-11ea-9c0a-216388252574.png">

So I am not sure whether always showing 5+1 words is the intended behavior and I misunderstood the description in `?create_oolong` or whether this is a bug.

**Comment by chainsawriot** [comment]
I can confirm this is a bug and very soon there will be a fix.

**Comment by chainsawriot** [comment]
Fixed. Once again, thanks for reporting this bug. CI passed.
Please install the newer dev version.

**Comment by bachl** [comment]
Perfect, thank you for the fast fix!
