### ISSUE TITLE
Using oolong on an rstudio.cloud session

### ISSUE THREAD

**Issue by danimadrid** [chainsawriot/oolong#30]
Hi, I wanted to incorporate oolong in a lab for a class I'm teaching this summer using projects hosted on rstudio.cloud, but I can't seem to have it run on there. 

```
Listening on http://127.0.0.1:4794
Warning: Error in value[[3L]]: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'miniUI-0.1.1.1'; `directoryPath` = '/tmp/work/miniUI/www'
  [No stack trace available]
```

Any thoughts on how to solve the issue? Here is the project https://rstudio.cloud/project/1450473

Thanks.

**Comment by chainsawriot** [comment]
This is very similar to #28 .

I have tested it on RStudio Cloud and a simple solution is to 

```r
update.packages(ask = FALSE)
install.packages("devtools")
devtools::install_github("chainsawriot/oolong")
```

**Comment by danimadrid** [comment]
Wonderful! 唔該晒!
