### ISSUE TITLE
Raterskipped one question -> error

### ISSUE THREAD

**Issue by sunosnoc** [chainsawriot/oolong#36]
Hi!
Thanks so much for creating this package!
For a scientific publication I use the oolong package to establish concurrent validity for a topic model.
One of the raters seems to have skipped one of the questions for the topic intrusion test, but was not redirected to the missing question when hitting "done". The test took 3 days and I really do not have the time to repeat the process again.
When using the summarize_oolong function on the locked test it throws me this error: 
"Result 52 must be a single dounle. not a double vector of length 0".
Is there any way to let the rater do the missing question without having to repeat the entire process?

Thanks!

**Comment by chainsawriot** [comment]
It is possible; but please contact me by e-mail (I hope you can understand that I don't want to make how to override the lock publicly).

**Comment by sunosnoc** [comment]
Thanks for replying so quickly! I contacted you via email!
