### ISSUE TITLE
Keep docvars in Gold Standard Test

### ISSUE THREAD

**Issue by msaeltzer** [chainsawriot/oolong#38]
I think it would be useful to keep quanteda docvars that are already stored in a corpus in the gold_stadata, so it is easier to compare gold standard to already implemented variables. Gives more flexibility to workflows. Simply adding a docvars=T argument and conditioning it on quanteda corpus class would be sufficient...

**Comment by chainsawriot** [comment]
@msaeltzer do you still need this?
