### ISSUE TITLE
summarise_oolong() always sets target_value = NULL

### ISSUE THREAD

**Issue by joon-e** [chainsawriot/oolong#59]
First: thanks for the amazing package!

I just ran across a bug when using `summarise_oolong()` instead of `summarize_oolong()` for gold standard tests, as it will return an error, regardless if target values were passed or not:

```
summarise_oolong(gs_test, target_value = 1:20)
```

```
New names:
* NA -> ...1
Warning in .summarize_oolong_gs(..., target_value = target_value) :
  target_value is NULL, only the reliability of the answers from the coder(s) are studied.
```

This is because in lines 95-97 of `oolong_summary.R`, where the synonymous function is defined, the value of `target_value` is not passed to the actual function `summarize_oolong()`, but set to `NULL` in said function call.

```
summarise_oolong <- function(..., target_value = NULL) {
    summarize_oolong(..., target_value = NULL)
}
``` 

So, just changing this to 
```
summarise_oolong <- function(..., target_value = NULL) {
    summarize_oolong(..., target_value = target_value)
}
``` 
should probably fix this, but let me know if I should properly test it and create a PR.

**Comment by chainsawriot** [comment]
@joon-e Thanks for reporting this and suggesting a solution to this. It's indeed a bug. I've fixed this. Please update to the latest version accordingly.
