### ISSUE TITLE
New commit for mybinder.org

### ISSUE THREAD

**Issue by rgaiacs** [chainsawriot/oolong#90]
I don't know why the image on mybinder.org has a broken installation of Quarto.

```
$ git rev-parse HEAD
aec557b6cc914842ab63562593aaba3aecb94bf1
$ quarto --version
cat: /home/jovyan/.quarto/opt/quarto/share/version: No such file or directory
```

https://github.com/user-attachments/assets/63ae0def-6a98-4200-893b-bba9cabc78a4

I tried to reproduce locally but things worked as expected.

Can we have a new commit to check things in mybinder.org? Thanks!

cc @arnim

**Comment by chainsawriot** [comment]
259cd87f85f033f744d075ffa0ef825894cfdfae
