### ISSUE TITLE
Oolong in Google Colab

### ISSUE THREAD

**Issue by LuigiC72** [chainsawriot/oolong#95]
Is there any possibility to use Oolong within a Google Colab session?
Thank you!
Best
Luigi

**Comment by chainsawriot** [comment]
It depends on what do you mean by "use `oolong`". One can certainly install and "use" `oolong` (e.g. do calculation with a coded object) on Google Colab using the R runtime. Whether or not one can run those `$do_*()` methods is [another story](https://forum.posit.co/t/hosting-shiny-app-on-google-colab/51845) (requires shiny). Google Colab is not designed to handle this, unless I was mistaken.
