### ISSUE TITLE
Nested link

### ISSUE THREAD

**Issue by rgaiacs** [chainsawriot/oolong#98]
Why did you write

```markdown
(Ying et al. 2021) [<doi:10.1017/pan.2021.33>](https://doi.org/10.1017/pan.2021.33) tests
```

in https://github.com/gesistsa/oolong/blob/ff0561d16ceac5ffe59605195bdb196895003ef7/methodshub.qmd#L13?

The snippet is render as

```html
<p>(Ying et al. 2021) <a href="https://doi.org/10.1017/pan.2021.33"><a href="doi:10.1017/pan.2021.33">doi:10.1017/pan.2021.33</a></a> tests.</p>
```

where you have a nested link.

**Comment by chainsawriot** [comment]
ok, it was automatically converted via `usemh`. So, I think for doi, `<doi:10.1017/pan.2021.33>` is actually sufficient? lemme test.

**Comment by chainsawriot** [comment]
https://github.com/gesistsa/usemh/blob/cb720f6c0403ae134c26ec0861b2ee2a5de1a9ab/R/usemh_method.R#L80-L84

**Comment by chainsawriot** [comment]
Interesting, my local quarto (1.6.39) renders it as:

```html
word set intrusion (Ying et al.&nbsp;2021) <a href="https://doi.org/10.1017/pan.2021.33">&lt;doi:10.1017/pan.2021.33&gt;</a> tests. 
```

But anyway, would this help?

```md
(Ying et al. 2021) [doi:10.1017/pan.2021.33](https://doi.org/10.1017/pan.2021.33)
```
